"""
Shared in-memory application state for the UI layer.

Gemini setup
------------
Set GEMINI_API_KEY in a .env file (or as a real environment variable) to
enable AI draft generation.  The optional GEMINI_MODEL variable selects the
model; it defaults to "gemini-2.5-flash".

Gmail setup
-----------
Place credentials.json and token.json in the project root (generated by
running gmail_auth.py once). The GmailClient will be initialised automatically.
"""

from __future__ import annotations

import logging
import os

from pathlib import Path

from dotenv import load_dotenv

from src.audit.audit_logger import AuditLogger
from src.auth.session_manager import SessionManager
from src.integration.factory import create_orchestrator
from src.orchestrator.agent_orchestrator import AgentOrchestrator
from src.permissions.permission_manager import PermissionManager

# Resolve .env relative to the project root (two levels up from src/ui/)
_ENV_PATH = Path(__file__).resolve().parent.parent.parent / ".env"
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
load_dotenv(dotenv_path=_ENV_PATH)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Gemini LLM client
# ---------------------------------------------------------------------------

def _build_llm_client():
    """Return a configured Gemini GenerativeModel, or None if no API key is set."""
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key or api_key == "your_api_key_here":
        logger.warning(
            "GEMINI_API_KEY not set — LLM draft generation is disabled. "
            "Add your key to the .env file and restart."
        )
        return None

    try:
        import google.generativeai as genai  # type: ignore
        genai.configure(api_key=api_key)
        model_name = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
        model = genai.GenerativeModel(model_name)
        logger.info("Gemini LLM client configured (model=%s)", model_name)
        return model
    except Exception as exc:
        logger.error("Failed to initialise Gemini client: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Gmail client
# ---------------------------------------------------------------------------

def _build_gmail_client():
    """
    Return a GmailClient loaded from token.json, or None if not available.

    Requires token.json (and credentials.json) in the project root.
    Run gmail_auth.py once to generate token.json.
    """
    token_path = _PROJECT_ROOT / "token.json"

    if not token_path.exists():
        logger.warning(
            "token.json not found — Gmail integration disabled. "
            "Run gmail_auth.py to authorise Gmail access."
        )
        return None

    try:
        import json
        from datetime import datetime, timezone
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request

        # Load using the built-in helper — correctly picks up all fields
        creds = Credentials.from_authorized_user_file(
            str(token_path),
            scopes=[
                "https://www.googleapis.com/auth/gmail.send",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
            ],
        )

        # Refresh if expired
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            # Save refreshed token back to file
            with open(token_path, "w") as f:
                f.write(creds.to_json())
            logger.info("Gmail token refreshed and saved.")

        # Build OAuthToken model for GmailClient
        from src.models.types import GmailScope, OAuthToken

        _SCOPE_MAP = {
            "https://www.googleapis.com/auth/gmail.send":     GmailScope.SEND,
            "https://www.googleapis.com/auth/gmail.readonly":  GmailScope.READONLY,
            "https://www.googleapis.com/auth/gmail.compose":   GmailScope.COMPOSE,
            "https://www.googleapis.com/auth/gmail.modify":    GmailScope.MODIFY,
        }
        scopes = [_SCOPE_MAP[s] for s in (creds.scopes or []) if s in _SCOPE_MAP]

        expiry = creds.expiry
        if expiry and expiry.tzinfo is None:
            expiry = expiry.replace(tzinfo=timezone.utc)
        if not expiry:
            expiry = datetime.now(tz=timezone.utc)

        oauth_token = OAuthToken(
            access_token=creds.token,
            refresh_token=creds.refresh_token or "",
            expires_at=expiry,
            scopes=scopes,
        )

        from src.gmail.gmail_client import GmailClient
        client = GmailClient(oauth_token=oauth_token)
        logger.info("Gmail client initialised (scopes=%s)", [s.value for s in scopes])
        return client

    except Exception as exc:
        logger.error("Failed to initialise Gmail client: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Singletons
# ---------------------------------------------------------------------------

audit_logger = AuditLogger()
session_manager = SessionManager(
    session_timeout_minutes=30,
    rate_limit_threshold=5,
    oauth_client_config=None,
)
permission_manager = PermissionManager(audit_logger=audit_logger)

_gmail_client = _build_gmail_client()

orchestrator: AgentOrchestrator = create_orchestrator(
    session_manager=session_manager,
    permission_manager=permission_manager,
    gmail_client=_gmail_client,
    llm_client=_build_llm_client(),
    audit_logger=audit_logger,
)

if _gmail_client:
    logger.info("Gmail integration: ENABLED")
else:
    logger.info("Gmail integration: DISABLED (simulated mode)")

# ---------------------------------------------------------------------------
# Background scheduler — auto-sends scheduled drafts at their send time
# ---------------------------------------------------------------------------

from src.scheduling.background_scheduler import BackgroundScheduler

_scheduler = BackgroundScheduler(
    scheduled_draft_manager=orchestrator._scheduled_draft_manager,
    gmail_client=_gmail_client,
    audit_logger=audit_logger,
)
_scheduler.start()

